export const AUTHENTICATE = "AUTHENTICATE";
export type AUTHENTICATE = typeof AUTHENTICATE;

export const UNAUTHENTICATE = "UNAUTHENTICATE";
export type UNAUTHENTICATE = typeof UNAUTHENTICATE;

export const CHECKUSER = "CHECKUSER";
export type CHECKUSER = typeof CHECKUSER;

export const ARTISTDETAILS = "ARTISTDETAILS";
export type ARTISTDETAILS = typeof ARTISTDETAILS;

export const ACCOUNTDETAILS = "ACCOUNTDETAILS";
export type ACCOUNTDETAILS = typeof ACCOUNTDETAILS;
