export const AUTHENTICATE = "AUTHENTICATE";
export type AUTHENTICATE = typeof AUTHENTICATE;

export const UNAUTHENTICATE = "UNAUTHENTICATE";
export type UNAUTHENTICATE = typeof UNAUTHENTICATE;

export const CHECKUSER = "CHECKUSER";
export type CHECKUSER = typeof CHECKUSER;

export const ARTISTDETAILS = "ARTISTDETAILS";
export type ARTISTDETAILS = typeof ARTISTDETAILS;

export const ACCOUNTDETAILS = "ACCOUNTDETAILS";
export type ACCOUNTDETAILS = typeof ACCOUNTDETAILS;

export const ADDCLIENT = "ADDCLIENT";
export type ADDCLIENT = typeof ADDCLIENT;

export const SETCLIENTS = "SETCLIENTS";
export type SETCLIENTS = typeof SETCLIENTS;

export const DELETECLIENT = "DELETECLIENT";
export type DELETECLIENT = typeof DELETECLIENT;

export const EDITCLIENT = "EDITCLIENT";
export type EDITCLIENT = typeof EDITCLIENT;
